#!/usr/bin/env python3
"""
BMP to BGR565 Image Struct Header File Converter

This script converts BMP images to C header files containing BGR565 pixel data arrays.
Generates both .h and .c files with uint16_t (16-bit, 5-6-5 format).

Usage:
    python convert.py <image.bmp> [output_name] [width] [height]

Examples:
    python convert.py image01.bmp
    python convert.py image01.bmp image01
    python convert.py image01.bmp image01 320 480
"""

import os
import sys
from pathlib import Path
from PIL import Image


class BMPToHeaderConverter:
    """Convert BMP images to C header files with BGR565 pixel data."""

    def __init__(self, bmp_file, output_name=None, width=None, height=None):
        """
        Initialize converter.

        Args:
            bmp_file: Path to input BMP file
            output_name: Base name for output files (without extension)
            width: Target width in pixels (optional, default: use original)
            height: Target height in pixels (optional, default: use original)
        """
        self.bmp_file = Path(bmp_file)

        if not self.bmp_file.exists():
            raise FileNotFoundError(f"BMP file not found: {bmp_file}")

        if not self.bmp_file.suffix.lower() == '.bmp':
            raise ValueError(f"File must be BMP format, got: {self.bmp_file.suffix}")

        # Use input filename as base if no output name provided
        self.output_name = output_name or self.bmp_file.stem

        # Open and process image
        img = Image.open(self.bmp_file)

        # Resize if dimensions provided
        if width is not None and height is not None:
            img = img.resize((width, height), Image.Resampling.LANCZOS)
            self.width = width
            self.height = height
        else:
            self.width = img.width
            self.height = img.height

        self.img = img
        self.pixels = self._extract_bgr_pixels()

    def _extract_bgr_pixels(self):
        """Extract BGR565 pixel data from image."""
        # Convert to RGB first if not already
        if self.img.mode != 'RGB':
            img_rgb = self.img.convert('RGB')
        else:
            img_rgb = self.img

        # Convert RGB to BGR565 pixel list
        pixels = []
        for y in range(self.height):
            row = []
            for x in range(self.width):
                r, g, b = img_rgb.getpixel((x, y))
                # Convert to 5-6-5 format
                # Blue: 5 bits (B >> 3)
                # Green: 6 bits (G >> 2)
                # Red: 5 bits (R >> 3)
                b5 = (b >> 3) & 0x1F
                g6 = (g >> 2) & 0x3F
                r5 = (r >> 3) & 0x1F
                # Pack into 16-bit BGR565: BBBBBGGGGGGRRRRR
                bgr565 = f"RGB({r5},{g6},{b5})"
                row.append(bgr565)
            pixels.append(row)

        return pixels

    def _get_c_variable_name(self):
        """Generate valid C variable name from filename."""
        # Replace invalid C identifier characters
        name = self.output_name.replace('-', '_').replace(' ', '_')
        # Ensure it doesn't start with a number
        if name[0].isdigit():
            name = f"image_{name}"
        return name

    def generate_header_file(self):
        """Generate C header file content."""
        var_name = self._get_c_variable_name()
        guard = f"{var_name.upper()}_H_"

        header = f"""/*! ***************************************************************************
 *
 * \\brief     Bitmap data for image: {self.bmp_file}
 * \\file      {self.output_name}.h
 * \\author    Generated by convert.py - made_by_ESE
 *
 *****************************************************************************/
#ifndef {guard}
#define {guard}

#include "tft_lcd.h"

// Bitmap dimensions and data: {self.width}x{self.height} pixels in BGR565 format (uint16_t)
#define {var_name.upper()}_BMP_WIDTH  {self.width}
#define {var_name.upper()}_BMP_HEIGHT {self.height}
extern const uint16_t {var_name}_bmp[{var_name.upper()}_BMP_HEIGHT][{var_name.upper()}_BMP_WIDTH];

#endif // {guard}

"""
        return header

    def generate_source_file(self):
        """Generate C source file content with image data."""
        var_name = self._get_c_variable_name()

        source = f"""/*! ***************************************************************************
 *
 * \\brief     Bitmap data for image: {self.bmp_file}
 * \\file      {self.output_name}.c
 * \\author    Generated by convert.py - made_by_ESE
 *
 *****************************************************************************/
#include "{self.output_name}.h"

// Bitmap pixel data: {self.width}x{self.height} pixels in BGR565 format (uint16_t)
const uint16_t {var_name}_bmp[{var_name.upper()}_BMP_HEIGHT][{var_name.upper()}_BMP_WIDTH] =
{{
"""

        # Add pixel data
        for y, row in enumerate(self.pixels):
            source += "    { "
            for x, pixel in enumerate(row):
                source += pixel
                if x < len(row) - 1:
                    source += ", "
            source += " }"
            if y < len(self.pixels) - 1:
                source += ","
            source += "\n"

        source += "};\n"

        return source

    def write_files(self, output_dir=None):
        """
        Write header and source files to disk.

        Args:
            output_dir: Output directory (default: same as input BMP file)
        """
        if output_dir is None:
            output_dir = self.bmp_file.parent
        else:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)

        # Write header file
        h_file = output_dir / f"{self.output_name}.h"
        with open(h_file, 'w') as f:
            f.write(self.generate_header_file())
        print(f"Generated: {h_file}")

        # Write source file
        c_file = output_dir / f"{self.output_name}.c"
        with open(c_file, 'w') as f:
            f.write(self.generate_source_file())
        print(f"Generated: {c_file}")

        return h_file, c_file

    def get_info(self):
        """Get image information."""
        return {
            'filename': self.bmp_file.name,
            'width': self.width,
            'height': self.height,
            'size_pixels': self.width * self.height,
            'size_bytes': self.width * self.height * 2,
            'output_name': self.output_name
        }


def print_usage():
    """Print usage information."""
    print("""
Usage: python convert.py <image.bmp> [output_name] [width] [height]

Convert a BMP image to C header and source files with BGR565 pixel data.

Arguments:
  image.bmp       Path to the input BMP image file (required)
  output_name     Base name for output files (optional, defaults to image filename)
  width           Target image width in pixels (optional)
  height          Target image height in pixels (optional)

Examples:
  python convert.py image01.bmp
  python convert.py image01.bmp image01
  python convert.py image01.bmp image01 320 480

Output:
  - <output_name>.h  (header file with extern declaration using uint16_t)
  - <output_name>.c  (source file with pixel data array)

The generated files use uint16_t (16-bit BGR565 format) from lcd_par_s035.h.

Requirements:
  - Python 3.6+
  - Pillow (PIL): pip install Pillow
    """)


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print_usage()
        sys.exit(1)

    bmp_file = sys.argv[1]
    output_name = sys.argv[2] if len(sys.argv) > 2 else None
    width = int(sys.argv[3]) if len(sys.argv) > 3 else None
    height = int(sys.argv[4]) if len(sys.argv) > 4 else None

    try:
        # Create converter
        converter = BMPToHeaderConverter(bmp_file, output_name, width, height)

        # Print image info
        info = converter.get_info()
        print(f"\nImage Information:")
        print(f"  Filename: {info['filename']}")
        print(f"  Dimensions: {info['width']}x{info['height']} pixels")
        print(f"  Total pixels: {info['size_pixels']}")
        print(f"  Data size: {info['size_bytes']} bytes (BGR565 format)")
        print(f"  Output name: {info['output_name']}")

        # Generate and write files
        print("\nGenerating output files...")
        converter.write_files()
        print("\nConversion complete!")

    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
