/*! ***************************************************************************
 *
 * \brief     Image data: image
 * \file      image.h
 * \author    Generated by convert.py
 *
 *****************************************************************************/
#ifndef IMAGE_H_
#define IMAGE_H_

#include "lcd_par_s035.h"

/* Image dimensions */
#define IMAGE_WIDTH  160
#define IMAGE_HEIGHT 120

/* Image data array - color_rgb888_t format (BGR, 24-bit) */
extern const color_rgb888_t image_data[120][160];

#endif // IMAGE_H_

