# Copyright 2024 NXP
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Disable board project basic segments
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.board_core_file=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.console=n
CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_HAS_PRJSEG_module.board.peripheral_sel=n
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n

# Disable device specific drivers configuration
CONFIG_MCUX_COMPONENT_driver.romapi=n
CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_COMPONENT_driver.edma_soc=n
CONFIG_MCUX_COMPONENT_driver.inputmux_connections=n
CONFIG_MCUX_COMPONENT_driver.reset=n
CONFIG_MCUX_COMPONENT_driver.trdc_soc=n

# Disable driver configuration
CONFIG_MCUX_COMPONENT_driver.common=n
CONFIG_MCUX_COMPONENT_driver.gpio=n
CONFIG_MCUX_COMPONENT_driver.lpuart=n
CONFIG_MCUX_COMPONENT_driver.mcx_spc=n
CONFIG_MCUX_COMPONENT_driver.port=n

#
# Middleware
#
CONFIG_MCUX_COMPONENT_middleware.usb.common_header=y
CONFIG_MCUX_COMPONENT_middleware.usb.device.common_header=y
CONFIG_MCUX_MISC_USB_DEVICE_GENERATE_CONFIG=y

#
# Device Configurations(usb_device_config.h)
#

#
# USB Hardware Configurations
#
CONFIG_USB_DEVICE_CONFIG_KHCI=1
CONFIG_USB_DEVICE_CONFIG_KHCI_DMA_ALIGN_BUFFER_LENGTH=64
CONFIG_USB_DEVICE_CONFIG_EHCI=0
CONFIG_USB_DEVICE_CONFIG_EHCI_MAX_DTD=16
CONFIG_USB_DEVICE_CONFIG_LPCIP3511FS=0
CONFIG_USB_DEVICE_CONFIG_LPCIP3511HS=0

#
# USB Class Configurations
#
CONFIG_USB_DEVICE_CONFIG_AUDIO=0
CONFIG_USB_DEVICE_CONFIG_CDC_ACM=0
CONFIG_USB_DEVICE_CONFIG_CDC_ECM=0
CONFIG_USB_DEVICE_CONFIG_CDC_RNDIS=0
CONFIG_USB_DEVICE_CONFIG_HID=1
CONFIG_USB_DEVICE_CONFIG_PRINTER=0
CONFIG_USB_DEVICE_CONFIG_MSC=0
CONFIG_USB_DEVICE_CONFIG_CCID=0
CONFIG_USB_DEVICE_CONFIG_VIDEO=0
CONFIG_USB_DEVICE_CONFIG_PHDC=0
CONFIG_USB_DEVICE_CONFIG_DFU=0
CONFIG_USB_DEVICE_CONFIG_MTP=0

#
# USB Miscellaneous Configurations
#
CONFIG_USB_DEVICE_CONFIG_SELF_POWER=y
CONFIG_USB_DEVICE_CONFIG_ENDPOINTS=4
# CONFIG_USB_DEVICE_CONFIG_GET_SOF_COUNT is not set
# CONFIG_USB_DEVICE_CONFIG_SOF_NOTIFICATIONS is not set
# CONFIG_USB_DEVICE_CONFIG_ERROR_HANDLING is not set
# CONFIG_USB_DEVICE_CONFIG_RETURN_VALUE_CHECK is not set
# CONFIG_USB_DEVICE_CONFIG_USE_TASK is not set
CONFIG_USB_DEVICE_CONFIG_MAX_MESSAGES=8
# CONFIG_USB_DEVICE_CONFIG_DETACH_ENABLE is not set
# CONFIG_USB_DEVICE_CONFIG_CDC_CIC_EP_DISABLE is not set
# CONFIG_USB_DEVICE_CONFIG_LOW_POWER_MODE is not set
# CONFIG_USB_DEVICE_CONFIG_REMOTE_WAKEUP is not set
CONFIG_USB_DEVICE_CONFIG_ROOT2_TEST=y
# CONFIG_USB_DEVICE_CONFIG_KEEP_ALIVE_MODE is not set
# CONFIG_USB_DEVICE_CONFIG_USB20_TEST_MODE is not set
# CONFIG_USB_DEVICE_CONFIG_CV_TEST is not set
# CONFIG_USB_DEVICE_CONFIG_COMPLIANCE_TEST is not set

# end of Device Configurations(usb_device_config.h)
