#!/usr/bin/env python3
"""
BMP to BGR Image Struct Header File Converter

This script converts BMP images to C header files containing BGR pixel data arrays.
Generates both .h and .c files with color_rgb888_t struct from lcd_par_s035.h.

Usage:
    python convert.py <image.bmp> [output_name] [width] [height] [-f {rgb888,bgr565}]

Examples:
    python convert.py image01.bmp
    python convert.py image01.bmp image01
    python convert.py image01.bmp image01 320 480
    python convert.py image01.bmp image01 320 480 --format bgr565
"""

import sys
import argparse
from pathlib import Path
from PIL import Image


class BMPToHeaderConverter:
    """Convert BMP images to C header files with BGR pixel data."""

    def __init__(self, bmp_file, output_name=None, width=None, height=None, output_format='rgb888'):
        """
        Initialize converter.

        Args:
            bmp_file: Path to input BMP file
            output_name: Base name for output files (without extension)
            width: Target width in pixels (optional, default: use original)
            height: Target height in pixels (optional, default: use original)
            output_format: Output pixel format ('rgb888' or 'bgr565')
        """
        self.bmp_file = Path(bmp_file)

        if not self.bmp_file.exists():
            raise FileNotFoundError(f"BMP file not found: {bmp_file}")

        if not self.bmp_file.suffix.lower() == '.bmp':
            raise ValueError(f"File must be BMP format, got: {self.bmp_file.suffix}")

        # Use input filename as base if no output name provided
        self.output_name = output_name or self.bmp_file.stem

        self.output_format = output_format.lower()
        if self.output_format not in {'rgb888', 'bgr565'}:
            raise ValueError(f"Unsupported format: {output_format}. Use 'rgb888' or 'bgr565'.")

        if (width is None) != (height is None):
            raise ValueError("Both width and height must be provided together")

        # Open and process image
        img = Image.open(self.bmp_file)

        # Resize if dimensions provided
        if width is not None and height is not None:
            img = img.resize((width, height), Image.Resampling.LANCZOS)
            self.width = width
            self.height = height
        else:
            self.width = img.width
            self.height = img.height

        self.img = img
        self.pixels = self._extract_bgr_pixels()

    def _extract_bgr_pixels(self):
        """Extract BGR pixel data from image."""
        # Convert to RGB first if not already
        if self.img.mode != 'RGB':
            img_rgb = self.img.convert('RGB')
        else:
            img_rgb = self.img

        # Convert RGB to BGR pixel list
        pixels = []
        for y in range(self.height):
            row = []
            for x in range(self.width):
                r, g, b = img_rgb.getpixel((x, y))
                # Store as BGR (Blue, Green, Red)
                row.append({'b': b, 'g': g, 'r': r})
            pixels.append(row)

        return pixels

    @staticmethod
    def _rgb_to_bgr565(r, g, b):
        """Pack 24-bit RGB channels into a 16-bit BGR565 value."""
        return ((b >> 3) << 11) | ((g >> 2) << 5) | (r >> 3)

    def _get_c_variable_name(self):
        """Generate valid C variable name from filename."""
        # Replace invalid C identifier characters
        name = self.output_name.replace('-', '_').replace(' ', '_')
        # Ensure it doesn't start with a number
        if name[0].isdigit():
            name = f"image_{name}"
        return name

    def generate_header_file(self):
        """Generate C header file content."""
        var_name = self._get_c_variable_name()
        guard = f"{var_name.upper()}_H_"

        if self.output_format == 'rgb888':
            include_section = '#include "lcd_par_s035.h"'
            data_comment = '/* Image data array - color_rgb888_t format (BGR, 24-bit) */'
            data_decl = f"extern const color_rgb888_t {var_name}_data[{self.height}][{self.width}];"
        else:
            include_section = '#include <stdint.h>'
            data_comment = '/* Image data array - packed BGR565 format (16-bit) */'
            data_decl = f"extern const uint16_t {var_name}_data[{self.height}][{self.width}];"

        header = f"""/*! ***************************************************************************
 *
 * \\brief     Image data: {self.output_name}
 * \\file      {self.output_name}.h
 * \\author    Generated by convert.py
 *
 *****************************************************************************/
#ifndef {guard}
#define {guard}

{include_section}

/* Image dimensions */
#define {var_name.upper()}_WIDTH  {self.width}
#define {var_name.upper()}_HEIGHT {self.height}

{data_comment}
{data_decl}

#endif // {guard}

"""
        return header

    def generate_source_file(self):
        """Generate C source file content with image data."""
        var_name = self._get_c_variable_name()

        if self.output_format == 'rgb888':
            data_type = 'color_rgb888_t'
            format_comment = 'BGR888'
        else:
            data_type = 'uint16_t'
            format_comment = 'packed BGR565'

        source = f"""/*! ***************************************************************************
 *
 * \\brief     Image data: {self.output_name}
 * \\file      {self.output_name}.c
 * \\author    Generated by convert.py
 *
 *****************************************************************************/
#include "{self.output_name}.h"

/* Image data: {self.width}x{self.height} pixels in {format_comment} format ({data_type}) */
const {data_type} {var_name}_data[{self.height}][{self.width}] = {{
"""

        # Add pixel data
        for y, row in enumerate(self.pixels):
            source += "    { "
            for x, (r, g, b) in enumerate(row):
                if self.output_format == 'rgb888':
                    source += f"{{0x{b:02x}, 0x{g:02x}, 0x{r:02x}}}"
                else:
                    bgr565 = self._rgb_to_bgr565(r, g, b)
                    source += f"0x{bgr565:04x}"
                if x < len(row) - 1:
                    source += ", "
            source += " }"
            if y < len(self.pixels) - 1:
                source += ","
            source += "\n"

        source += "};\n"

        return source

    def write_files(self, output_dir=None):
        """
        Write header and source files to disk.

        Args:
            output_dir: Output directory (default: same as input BMP file)
        """
        if output_dir is None:
            output_dir = self.bmp_file.parent
        else:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)

        # Write header file
        h_file = output_dir / f"{self.output_name}.h"
        with open(h_file, 'w') as f:
            f.write(self.generate_header_file())
        print(f"Generated: {h_file}")

        # Write source file
        c_file = output_dir / f"{self.output_name}.c"
        with open(c_file, 'w') as f:
            f.write(self.generate_source_file())
        print(f"Generated: {c_file}")

        return h_file, c_file

    def get_info(self):
        """Get image information."""
        return {
            'filename': self.bmp_file.name,
            'width': self.width,
            'height': self.height,
            'size_pixels': self.width * self.height,
            'size_bytes': self.width * self.height * (3 if self.output_format == 'rgb888' else 2),
            'output_name': self.output_name,
            'format': self.output_format
        }


def print_usage():
    """Print usage information."""
    print("""
Usage: python convert.py <image.bmp> [output_name] [width] [height] [-f {rgb888,bgr565}]

Convert a BMP image to C header and source files with BGR pixel data.

Arguments:
  image.bmp       Path to the input BMP image file (required)
  output_name     Base name for output files (optional, defaults to image filename)
  width           Target image width in pixels (optional)
  height          Target image height in pixels (optional)
    -f, --format    Output format: rgb888 (default) or bgr565

Examples:
  python convert.py image01.bmp
  python convert.py image01.bmp image01
  python convert.py image01.bmp image01 320 480
    python convert.py image01.bmp image01 320 480 --format bgr565

Output:
    - <output_name>.h  (header with extern declaration)
    - <output_name>.c  (source file with pixel data array)

Formats:
    - rgb888: uses color_rgb888_t from lcd_par_s035.h
    - bgr565: uses packed uint16_t BGR565 values

Requirements:
  - Python 3.6+
  - Pillow (PIL): pip install Pillow
    """)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('bmp_file', nargs='?')
    parser.add_argument('output_name', nargs='?')
    parser.add_argument('width', nargs='?', type=int)
    parser.add_argument('height', nargs='?', type=int)
    parser.add_argument('-f', '--format', dest='output_format', choices=['rgb888', 'bgr565'], default='rgb888')
    parser.add_argument('-h', '--help', action='store_true')

    args = parser.parse_args()

    if args.help or args.bmp_file is None:
        print_usage()
        sys.exit(1)

    if (args.width is None) != (args.height is None):
        print("Error: width and height must be provided together")
        print_usage()
        sys.exit(1)

    bmp_file = args.bmp_file
    output_name = args.output_name
    width = args.width
    height = args.height
    output_format = args.output_format

    try:
        # Create converter
        converter = BMPToHeaderConverter(bmp_file, output_name, width, height, output_format)

        # Print image info
        info = converter.get_info()
        print(f"\nImage Information:")
        print(f"  Filename: {info['filename']}")
        print(f"  Dimensions: {info['width']}x{info['height']} pixels")
        print(f"  Total pixels: {info['size_pixels']}")
        print(f"  Data size: {info['size_bytes']} bytes ({info['format']} format)")
        print(f"  Output name: {info['output_name']}")
        print(f"  Output format: {info['format']}")

        # Generate and write files
        print("\nGenerating output files...")
        converter.write_files()
        print("\nConversion complete!")

    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
